import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const lps = sqliteTable("lps", { id: text("id").primaryKey(), name: text("name").notNull(), entityName: text("entity_name"), email: text("email").notNull().unique(), notes: text("notes"), active: integer("active", { mode: "boolean" }).notNull().default(true) });
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), role: text("role", { enum: ["gp", "lp"] }).notNull(), lpId: text("lp_id").references(() => lps.id), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const magicLinkTokens = sqliteTable("magic_link_tokens", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), tokenHash: text("token_hash").notNull().unique(), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(), usedAt: integer("used_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const funds = sqliteTable("funds", { id: text("id").primaryKey(), name: text("name").notNull(), vintageYear: integer("vintage_year").notNull(), sizeCents: integer("size_cents").notNull(), currency: text("currency").notNull().default("USD"), status: text("status", { enum: ["investing", "harvesting", "closed"] }).notNull() });
export const lpFundPositions = sqliteTable("lp_fund_positions", { id: text("id").primaryKey(), lpId: text("lp_id").notNull().references(() => lps.id), fundId: text("fund_id").notNull().references(() => funds.id), committedCents: integer("committed_cents").notNull(), calledCents: integer("called_cents").notNull(), distributedCents: integer("distributed_cents").notNull(), ownershipPct: real("ownership_pct").notNull() }, t => [uniqueIndex("lp_fund_unique").on(t.lpId, t.fundId)]);
export const companies = sqliteTable("companies", { id: text("id").primaryKey(), name: text("name").notNull(), website: text("website"), logoUrl: text("logo_url"), description: text("description"), sectorTags: text("sector_tags", { mode: "json" }).$type<string[]>(), status: text("status", { enum: ["active", "exited", "written_off"] }).notNull() });
export const fundCompanyPositions = sqliteTable("fund_company_positions", { id: text("id").primaryKey(), fundId: text("fund_id").notNull().references(() => funds.id), companyId: text("company_id").notNull().references(() => companies.id), instrumentType: text("instrument_type", { enum: ["safe", "equity", "note"] }).notNull(), costBasisCents: integer("cost_basis_cents").notNull(), currentMarkCents: integer("current_mark_cents").notNull(), markDate: text("mark_date").notNull(), shares: integer("shares"), proRataRights: integer("pro_rata_rights", { mode: "boolean" }).notNull().default(false), proRataNotes: text("pro_rata_notes"), tags: text("tags", { mode: "json" }).$type<string[]>() }, t => [uniqueIndex("fund_company_unique").on(t.fundId, t.companyId)]);
export const updates = sqliteTable("updates", { id: text("id").primaryKey(), fundId: text("fund_id").notNull().references(() => funds.id), title: text("title").notNull(), quarter: text("quarter").notNull(), status: text("status", { enum: ["draft", "published"] }).notNull().default("draft"), publishedAt: integer("published_at", { mode: "timestamp" }), introText: text("intro_text"), closingText: text("closing_text") });
export const updateSections = sqliteTable("update_sections", { id: text("id").primaryKey(), updateId: text("update_id").notNull().references(() => updates.id), companyId: text("company_id").notNull().references(() => companies.id), blurb: text("blurb").notNull(), sortOrder: integer("sort_order").notNull() });
export const settings = sqliteTable("settings", { key: text("key").primaryKey(), value: text("value", { mode: "json" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() });
